### ISSUE TITLE
Cast exception Double to Long

### ISSUE THREAD

**Issue by xcymax** [yahoo/android-range-seek-bar#1]
I tried the widget with Long datatype but it gives a cast exception:
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long

At this line:
listener.onRangeSeekBarValuesChanged(this, getSelectedMinValue(), getSelectedMaxValue());

Here is my initialiser code:
```
private RangeSeekBar<Long> mSeekBar;
mSeekBar = (RangeSeekBar<Long>) rootView.findViewById(R.id.add_segment_range_bar);
// Set up the seek bar
mSeekBar.setRangeValues(0L, 100L);
```
This is my listener code:
```
mSeekBar.setOnRangeSeekBarChangeListener(new RangeSeekBar.OnRangeSeekBarChangeListener<Long>() {
                    @Override
                    public void onRangeSeekBarValuesChanged(RangeSeekBar<?> bar, Long minValue, Long maxValue) {
                        Log.d(TAG, "onRangeSeekBarValuesChanged");
                    }
                });
```

I had a look into it and the `setRangesValues(double minValue, double maxValue)` is being called, I'm not that well versed with Java casting and boxing/unboxing but I just commented out that function and it seems to work now. 

Anything I missed to get it to specifically work with long?

**Comment by anothem** [comment]
PR above should fix the problem. 
If you're trying to work with very large values, you might still get some UI issues, but otherwise should be supported fine now. Let me know if otherwise!
