### ISSUE TITLE
usage of range-seek-bar in single thumb mode

### ISSUE THREAD

**Issue by wirthual** [yahoo/android-range-seek-bar#10]
Hello, first thank you for sharing this project with us.

I have one issue, because I do not really get how to use the seek bar in single thumb mode. I cant figure out how to use it. I was expecting that there is only one method for setSelectedValue. But instead there are still 2 Methods for max and min.

How do i use a bar in single Thumb mode properly? Maybe you can add a short example to your docu. That would be great :)

**Comment by anothem** [comment]
Tracked [here](https://github.com/anothem/android-range-seek-bar/issues/10)
