### ISSUE TITLE
Change Range Interval on RSB

### ISSUE THREAD

**Issue by AldioFirando** [yahoo/android-range-seek-bar#14]
How to make this RSB have an interval?
For example I have range 0 - 100.000 and want this RSB change 5000 every sliding..
I have looking on RSB java file and I can't found how to change this interval,,

Thanks

**Comment by anothem** [comment]
Yeah, I'm afraid that's not currently supported, but definitely something that could be added.

**Comment by AldioFirando** [comment]
How about make this RSB use TIME like 9 AM until 10 PM? any suggest?

Thanks

**Comment by anothem** [comment]
Tracked here: https://github.com/anothem/android-range-seek-bar/issues/9
