### ISSUE TITLE
How to do it seek_thumb not hiding at the maximum or minimum value?

### ISSUE THREAD

**Issue by leahov** [yahoo/android-range-seek-bar#16]
Hi!
Thank you for a great UI-component. Please tell me how to do it seek_thumb not hiding at the maximum or minimum value? 
(Sorry for my English)

**Comment by anothem** [comment]
Hi Leahov, 

When you say not hiding, do you mean that you do not want the drawable to change when the range is min/max? 

Thanks,
Alex

**Comment by leahov** [comment]
Yes, exactly

**Comment by anothem** [comment]
Well, there is no way to configure it to do that at the moment.
 
If you want to edit the code directly for this, just replace this if statement (https://github.com/yahoo/android-range-seek-bar/blob/master/rangeseekbar/src/main/java/com/yahoo/mobile/client/android/util/RangeSeekBar.java#L560-L564) with https://github.com/yahoo/android-range-seek-bar/blob/master/rangeseekbar/src/main/java/com/yahoo/mobile/client/android/util/RangeSeekBar.java#L563. 
This will still make the text disappear, if you don't want that either, also remove
https://github.com/yahoo/android-range-seek-bar/blob/master/rangeseekbar/src/main/java/com/yahoo/mobile/client/android/util/RangeSeekBar.java#L501

That should do it.

**Comment by leahov** [comment]
Thank you very match!
