### ISSUE TITLE
Set steps

### ISSUE THREAD

**Issue by bartbergmans** [yahoo/android-range-seek-bar#18]
Is it possible to set steps for the range seekbar? For example, if I set the step to 5 I only can choose:
0 - 5 - 10 - 15 - 20 etc.?

**Comment by anothem** [comment]
Not possible at the moment, but would be good to have, similar to https://github.com/yahoo/android-range-seek-bar/issues/9. I'll get around to it soon if no one PRs it.

**Comment by bartbergmans** [comment]
Oke, I am now using the following code in the `OnRangeSeekBarChangeListener` with `notifyWhileDragging` enabled.

    Number max = (Number)maxValue;
    max = Math.round(((int)max / 100) * 100);

**Comment by anothem** [comment]
Tracked [here](https://github.com/anothem/android-range-seek-bar/issues/9)
