### ISSUE TITLE
Remove ic_launcher.png from library

### ISSUE THREAD

**Issue by smer4ik** [yahoo/android-range-seek-bar#21]
Library does not need ic_launcher.png. Including it causes build errors in gradle 1.2.3 such as this:

build/intermediates/res/debug/drawable-hdpi-v4/ic_launcher.png: error: Duplicate file.
builder/intermediates/res/debug/drawable-hdpi/ic_launcher.png: Original is here. The version qualifier may be implied.  

https://plus.google.com/+DanBachelderZumper/posts/YVuLY7rod6M

**Comment by anothem** [comment]
This is sorted in the project's new home, this repo is no longer maintained.  https://github.com/anothem/android-range-seek-bar
