### ISSUE TITLE
Hide labels

### ISSUE THREAD

**Issue by bartbergmans** [yahoo/android-range-seek-bar#24]
Will it be possible to hide the min and max labels from the slider?

To achieve this add this to the init method:

        mHideLabel = a.getBoolean(R.styleable.RangeSeekBar_hideThumb, false);

        mTextSize = PixelUtil.dpToPx(context, DEFAULT_TEXT_SIZE_IN_DP);
        if(!mHideLabel) {
            mDistanceToTop = PixelUtil.dpToPx(context, DEFAULT_TEXT_DISTANCE_TO_TOP_IN_DP);
        } else {
            mDistanceToTop = 0;
        }

And this to the bottom of onDraw:

        if(!mHideLabel) {
            if (!mSingleThumb) {
                canvas.drawText(minText,
                        normalizedToScreen(normalizedMinValue) - minTextWidth * 0.5f,
                        mDistanceToTop + mTextSize,
                        paint);

            }

            canvas.drawText(maxText,
                    normalizedToScreen(normalizedMaxValue) - maxTextWidth * 0.5f,
                    mDistanceToTop + mTextSize,
                    paint);
        }

**Comment by dbachelder** [comment]
I have added that feature as well as some others:

https://github.com/yahoo/android-range-seek-bar/pull/23

waiting for comment from maintainers

**Comment by bartbergmans** [comment]
When can I get that update with gradle?

**Comment by dbachelder** [comment]
You can get it now with jitpack.io
```
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
```

```
dependencies {
  compile 'com.github.dbachelder:android-range-seek-bar:12dbf35e83'
}
```

but keep in mind I will delete my fork if/when this gets merged

**Comment by bartbergmans** [comment]
How long could that take?

**Comment by dbachelder** [comment]
no clue.. never contributed to a yahoo project before. I'm using it in our app with jitpack as above.

**Comment by bartbergmans** [comment]
Ok, thanks!

**Comment by bartbergmans** [comment]
I'm now using your toolbar. It has everything I need. It's perfect <3 Thanks a lot!

**Comment by anothem** [comment]
@dbachelder, I am psyched about your PR, can't wait to look at it carefully and get it merged! Thanks a bunch for it :) 
Just dealing with a few issues at the moment (unrelated to your work) about how we'll be maintaining this project going forward. As soon as we sort this out, your PRs are first on the list! Should be all taken care of in the next few days, apologies for the delay, please bare with me as I sort this out.

**Comment by dbachelder** [comment]
@anothem any updates?

**Comment by anothem** [comment]
@dbachelder we're moving the home for this project, I will continue maintaining it on my own account. 
Just pushed this up a minute ago: https://github.com/yahoo/android-range-seek-bar/pull/25

I'm no longer at Yahoo so that has created difficulties maintaining it here (e.g. I can't merge your PRs at the moment). I've already forked here: https://github.com/anothem/android-range-seek-bar
If you want to get these looked at right away, the best thing to do is to reopen them against my fork and I will review and merge ASAP. Otherwise, whenever I get write access back to this repo, I will do it here as well and then just pull them across to the new fork, but I don't know exactly when that will be.

**Comment by dbachelder** [comment]
@anothem I have resubmitted the PR to the new home.

**Comment by anothem** [comment]
Thanks @dbachelder, appreciate it! Sorry for the delay and mixup.

**Comment by dbachelder** [comment]
no worries

**Comment by anothem** [comment]
This is now fixed at the project's new home (https://github.com/anothem/android-range-seek-bar) and available on the SNAPSHOT build.
