### ISSUE TITLE
Change Position on Click of a Button

### ISSUE THREAD

**Issue by devesh23** [yahoo/android-range-seek-bar#26]
How can I change position on click of a button, currently the code which I am using gives me Null Object reference

ViewGroup layout=(ViewGroup)v.findViewById(R.id.seekbar);
                RangeSeekBar seekbar=(RangeSeekBar)layout.getChildAt(0);
               seekbar.setSelectedMinValue(Integer.valueOf(ed.getText().toString()));
                seekbar.setSelectedMaxValue(Integer.valueOf(ed2.getText().toString()));

It is giving error in the second line. And I have already ruled out the possibility of no object created. the above code is being called from OnClickListener of Button

**Comment by dbachelder** [comment]
what does the layout.xml look like?

**Comment by devesh23** [comment]
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/seekbar"
        android:orientation="vertical"
        android:layout_below="@+id/textView1"
        />
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/SeekBarValues"
        android:orientation="horizontal"
        android:layout_below="@id/seekbar"
        android:weightSum="3">
        <EditText
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            android:id="@+id/MinValue"
            android:inputType="text"
            android:layout_weight="1"
            android:gravity="center_horizontal"
            android:layout_marginStart="10dp"
            android:layout_marginLeft="10dp" />
        <EditText
            android:layout_width="0dp"
            android:id="@+id/MaxValue"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            android:inputType="text"
            android:layout_weight="1"
            android:gravity="center_horizontal"
            android:layout_marginEnd="10dp"
            android:layout_marginRight="10dp" />
        <Button
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            android:layout_weight="1"
            android:text="Set"
            android:gravity="center_horizontal|center_vertical"
            android:id="@+id/set" />
    </LinearLayout>


I have attached the view using a LinearLayout and The button is in another Linear Layout

**Comment by devesh23** [comment]
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/seekbar"
        android:orientation="vertical"
        android:layout_below="@+id/textView1"
        />
       <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/SeekBarValues"
        android:orientation="horizontal"
        android:layout_below="@id/seekbar"
        android:weightSum="3">
            <EditText
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            android:id="@+id/MinValue"
            android:inputType="text"
            android:layout_weight="1"
            android:gravity="center_horizontal"
            android:layout_marginStart="10dp"
            android:layout_marginLeft="10dp" />
              <EditText
            android:layout_width="0dp"
            android:id="@+id/MaxValue"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            android:inputType="text"
            android:layout_weight="1"
            android:gravity="center_horizontal"
            android:layout_marginEnd="10dp"
            android:layout_marginRight="10dp" />
            <Button
             android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            android:layout_weight="1"
            android:text="Set"
            android:gravity="center_horizontal|center_vertical"
            android:id="@+id/set" />
          </LinearLayout>

**Comment by dbachelder** [comment]
I'm confused... there is no RangeSeekBar in that layout.

**Comment by dbachelder** [comment]
Also, the official version of this library is now here:

https://github.com/anothem/android-range-seek-bar

**Comment by devesh23** [comment]
I didnt get you, from where I saw the code, they attached the seekbar using Addview method

**Comment by devesh23** [comment]
Should I download the xml file mentioned in google codeprojects of this same project?

**Comment by dbachelder** [comment]
Check out the demo app in the repo I linked to above.

**Comment by devesh23** [comment]
Okay

**Comment by dbachelder** [comment]
If you still have issues open a ticket there. this yahoo repo is now deprecated in favor of that one.

**Comment by devesh23** [comment]
Thank you for your support :)
