### ISSUE TITLE
Gradle Icon duplication issue.

### ISSUE THREAD

**Issue by Tukajo** [yahoo/android-range-seek-bar#27]
Keeping icons in your project that is compiled by the dependencies is causing this issue, check out the answer too:

http://stackoverflow.com/questions/29965398/gradle-finished-with-non-zero-exit-value-1-ic-launcher-png-error-duplicate-fi

**Comment by dbachelder** [comment]
duplicates https://github.com/yahoo/android-range-seek-bar/issues/27

**Comment by anothem** [comment]
Correction: duplicates https://github.com/yahoo/android-range-seek-bar/issues/21 
@Tukajo, if you grab the latest from https://github.com/anothem/android-range-seek-bar this issue is fixed. It will be going out on JCenter soon as well.
