### ISSUE TITLE
Mimimum range difference and maximum range difference

### ISSUE THREAD

**Issue by bhuvneshvarma** [yahoo/android-range-seek-bar#28]
Can i set the minimum range difference and maximum range difference between the thumbs?

**Comment by anothem** [comment]
No, it's not possible at the moment

**Comment by anothem** [comment]
Tracked here: https://github.com/anothem/android-range-seek-bar/issues/5

**Comment by bhuvneshvarma** [comment]
is there any other library for doing that?
