### ISSUE TITLE
Don't activate Slider-Thumbs if at min or max

### ISSUE THREAD

**Issue by georgbachmann** [yahoo/android-range-seek-bar#8]
Not sure what issue #4 means, so I'll open a new one.
It would be nice to have a setting so that f.e. the max thumb does not show up as "active" if I only moved the min thumb.

**Comment by georgbachmann** [comment]
I implemented this feature for me... I could add a pull request if it's a wanted feature?!?

**Comment by anothem** [comment]
This is indeed different from https://github.com/yahoo/android-range-seek-bar/issues/4, that's more of a bug for the singleThumb mode. 
Yes, I could see why someone would want that, I think it would be a good option! 

If you have a pull request, I would love to see it! I think it should be a non-default behaviour and easily backwards compatible (so it doesn't change automatically for projects already using this as it is) and should be enabled by either code or XML configuration. But glad to see a PR with what you have and work together to get it there :)

**Comment by georgbachmann** [comment]
Nice, I'm not at home right now but I'll make you a pull request on that next week.

**Comment by anothem** [comment]
Tracked [here](https://github.com/anothem/android-range-seek-bar/issues/12)
A PR would still be welcome for this if you've already done it :)
